language: csharp
solution: src/Elasticsearch.sln
script: ./build.sh test
dist: trusty
mono: 4.6.2
dotnet: 2.0.3
env:
  global:     
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
