version: 1.0.{build}
image:
    - Visual Studio 2019
test: off
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
    - cmd: choco install dotnet-5.0-sdk --version 5.0.100
build_script:
    - cmd: build.bat canary

nuget:
    disable_publish_on_pr: true

for:

    - branches:
          only:
              - /^(master|\d+\.x)$/
      artifacts:
          - path: .\build\output\*.nupkg
            name: NuGet
