jobs:
- job: LinuxUnitTests
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            sudo apt install -y apt-transport-https ca-certificates
            echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
            sudo apt -y update
            sudo apt install -y mono-devel msbuild fsharp
            sudo apt-get install -y dotnet-sdk-2.2
    displayName: Apt install dependencies
  - script: ./build.sh test-one skipdocs
    displayName: 'build and unit test'
  - task: PublishTestResults@2
    inputs:
        testRunner: VSTest
        testResultsFiles: 'src/Tests/Tests/**/*.trx'
        testRunTitle: Linux Unit Tests

- job: WindowsCanaryTests
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: build.bat canary skipdocs
    displayName: 'build and unit test'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: 'src/Tests/Tests/**/*.trx'
      testRunTitle: Windows Unit Tests

- job: WindowsIntegrationTests
  dependsOn: WindowsCanaryTests
  pool:
      vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 5
    matrix:
      es7:
        esVersion: '7.0.0-beta1'
  steps:
      - script: 'build.bat integrate $(esVersion) "readonly,writable,bool,xpack" skipdocs'
        displayName: '$(esVersion) integration tests'
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
            testRunner: VSTest
            testResultsFiles: 'src/Tests/Tests/**/*.trx'
            testRunTitle: '$(esVersion)  Integration Tests'
