jobs:
- job: LinuxUnitTests
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    inputs:
        version: '3.0.100'
  - script: ./build.sh test-one
    displayName: 'build and unit test'
  - task: PublishTestResults@2
    inputs:
        testRunner: VSTest
        testResultsFiles: 'src/Tests/Tests/**/*.trx'
        testRunTitle: Linux Unit Tests

- job: WindowsCanaryTests
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '3.0.100'
  - script: build.bat canary
    displayName: 'build and unit test'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: 'src/Tests/Tests/**/*.trx'
      testRunTitle: Windows Unit Tests

- job: WindowsIntegrationTests
  dependsOn: WindowsCanaryTests
  pool:
      vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 5
    matrix:
      es682:
        esVersion: '6.8.16'
      es672:
        esVersion: '6.7.2'
      es662:
        esVersion: '6.6.2'
      es654:
        esVersion: '6.5.4'
      es642:
        esVersion: '6.4.3'
      es632:
        esVersion: '6.3.2'
      es624:
        esVersion: '6.2.4'
      es614:
        esVersion: '6.1.4'
      es601:
        esVersion: '6.0.1'
  steps:
      - task: UseDotNet@2
        inputs:
            version: '3.0.100'
      - script: 'build.bat integrate-one $(esVersion) "readonly,writable,bool,xpack"'
        displayName: '$(esVersion) windows integration tests'
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
            testRunner: VSTest
            testResultsFiles: 'src/Tests/Tests/**/*.trx'
            testRunTitle: '$(esVersion) Windows Integration Tests'
            
- job: LinuxIntegrationTests
  dependsOn: LinuxUnitTests
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 5
    matrix:
      es682:
        esVersion: '6.8.16'
      es672:
        esVersion: '6.7.2'
      es662:
        esVersion: '6.6.2'
      es654:
        esVersion: '6.5.4'
      es642:
        esVersion: '6.4.3'
      es632:
        esVersion: '6.3.2'
      es624:
        esVersion: '6.2.4'
      es614:
        esVersion: '6.1.4'
      es601:
        esVersion: '6.0.1'
  steps:
      - task: UseDotNet@2
        inputs:
            version: '3.0.100'
      - script: './build.sh integrate-one $(esVersion) "readonly,writable"'
        displayName: '$(esVersion) linux integration tests'
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
            testRunner: VSTest
            testResultsFiles: 'src/Tests/Tests/**/*.trx'
            testRunTitle: '$(esVersion) Linux Integration Tests'
