trigger:
  batch: true
  branches:
    include:
    - master
    - "*.x"

pr:
  autoCancel: true
  branches:
    exclude:
    - "backport-*" 

- job: WindowsIntegrationTests
  dependsOn: WindowsCanaryTests
  pool:
      vmImage: 'windows-2019'
  strategy:
    maxParallel: 5
    matrix:
      es7:
        esVersion: '7.0.0'
      es71:
        esVersion: '7.1.0'
      es72:
        esVersion: '7.2.0'
      es73:
        esVersion: '7.3.0'
      es74:
        esVersion: '7.4.0'
      es75:
        esVersion: '7.5.0'
      es76:
        esVersion: '7.6.0'
      es77:
        esVersion: '7.7.0'
      es78:
        esVersion: '7.8.0'
      es79:
        esVersion: '7.9.0'
      es710:
        esVersion: '7.10.0'
      es711:
        esVersion: '7.11.0'
      es712:
        esVersion: '7.12.0-SNAPSHOT'
      latest7:
        esVersion: 'latest-7'
  steps:
    - script: 'build.bat integrate-one $(esVersion) "readonly,writable,bool,xpack"'
      displayName: '$(esVersion) windows integration tests'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
          testRunner: VSTest
          testResultsFiles: 'tests/Tests/**/*.trx'
          testRunTitle: '$(esVersion) Windows Integration Tests'
            
- job: LinuxIntegrationTests
  dependsOn: LinuxUnitTests
  pool:
      vmImage: 'ubuntu-20.04'
  strategy:
      maxParallel: 5
      matrix:
        es7:
          esVersion: '7.0.0'
        es71:
          esVersion: '7.1.0'
        es72:
          esVersion: '7.2.0'
        es73:
          esVersion: '7.3.0'
        es74:
          esVersion: '7.4.0'
        es75:
          esVersion: '7.5.0'
        es76:
          esVersion: '7.6.0'
        es77:
          esVersion: '7.7.0'
        es78:
          esVersion: '7.8.0'
        es79:
          esVersion: '7.9.0'
        es710:
          esVersion: '7.10.0'
        es711:
          esVersion: '7.11.0'
        es712:
          esVersion: '7.12.0-SNAPSHOT'
        latest7:
          esVersion: 'latest-7'
  steps:
    - task: UseDotNet@2
      inputs:
          version: '5.0.103'
    - script: './build.sh integrate-one $(esVersion) "readonly,writable"'
      displayName: '$(esVersion) linux integration tests'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
          testRunner: VSTest
          testResultsFiles: 'tests/Tests/**/*.trx'
          testRunTitle: '$(esVersion) Linux Integration Tests'
