name: Code Generation 
on:
  schedule:
    - cron: "0 0/2 * * *"
  push:
    branches:
      - 'feature/master/automate-codegen'


jobs:
  active-branches:
    runs-on: ubuntu-latest

    steps:
      - id: dump-branches
        run: 
          curl -s https://artifacts-api.elastic.co/v1/branches  | jq "[ .branches[] | select(. | startswith(\"6\") | not) ]" > branches.json
      - id: set-matrix
        run: echo "::set-output name=matrix::$(cat branches.json)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      
  codegen:
    name: Assemble
    needs: active-branches
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.active-branches.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ matrix.branch }}"
      - run: "echo ${{ matrix.branch }}"
        name: Code Gen ${{ matrix.branch }}
      # - run: "./.ci/make.sh codegen ${{ matrix.branch }}"
      #  name: Code Gen ${{ matrix.stack_version }}