name: CI


on:
  push:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - run: ./build.sh test --report
        name: Test
      - name: Test Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'build/output/junit-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  # Packages nuget packages first and then uses the nuget packages to test
  # Also builds versioned nuget packages
  canary-tests:
    name: Canary Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - run: ./build.sh canary --report
        name: Test
      - name: Test Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'build/output/junit-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # Github packages requires authentication, this is likely going away in the future so for now we publish to feedz.io
      # Only runs on builds on heads
      - run: dotnet nuget push 'build/output/*.nupkg' -k ${{secrets.FEEDZ_IO_API_KEY}} -s https://f.feedz.io/elastic/all/nuget/index.json --skip-duplicate --no-symbols true
        name: publish canary packages to feedz.io
        if: github.event_name == 'push' && startswith(github.ref, 'refs/heads')

