name: Unified Release


on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
  push:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
    branches:
      - main
      - master
      - '[0-9]+.[0-9]+'
      - '[0-9]+.x'

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack_version: [ '8.0.0-SNAPSHOT']
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: make-docker-cache-{hash}
          restore-keys: |
              make-docker-cache-
            
      - run: "./.ci/make.sh assemble ${{ matrix.stack_version }}"
        name: ${{ matrix.stack_version }}
          
