name: CI


on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
  push:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - run: ./build.sh test --report
        name: Test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '/build/output/junit-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
